name: Buf CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Determine the branch name
        run: echo "Current branch is $GITHUB_REF_NAME"
      - name: Switch to the current branch
        run: |
          git checkout $GITHUB_REF_NAME
      - run: ./build.sh generate
      - run: |
            git config --global user.email "github-actions[bot]"
            git config --global user.name "github-actions[bot]@users.noreply.github.com"
      - run: |
          git add api/
          git commit -m "automated code generation" || echo "No changes to commit"
      - run: git push origin $GITHUB_REF_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: false
          github_token: ${{ secrets.GITHUB_TOKEN }}